#!/bin/bash


sudo apt update
sudo apt install build-essential libboost-all-dev autoconf automake libtool doxygen graphviz g++ python-dev autotools-dev libicu-dev libbz2-dev flex bison qt5-default libfontconfig1-dev libaudio-dev libxt-dev libglib2.0-dev libxi-dev libxrender-dev python3 python3-pip python3-setuptools python3-numpy python3-matplotlib

mkdir SS2D

cd SS2D

git clone https://github.com/rcsoccersim/rcssmonitor
git clone https://github.com/rcsoccersim/rcssserver
git clone https://github.com/helios-base/soccerwindow2
git clone https://github.com/helios-base/librcsc
git clone https://github.com/helios-base/fedit2
git clone https://github.com/Farzin-Negahbani/Namira-LogAnalyzer

cd librcsc
./bootstrap
./configure
make
sudo make install
sudo ldconfig
cd ..

cd rcssserver
./bootstrap
./configure
make
sudo make install
sudo ldconfig
cd ..

cd rcssmonitor
./bootstrap
./configure
make
sudo make install
sudo ldconfig
cd ..

cd soccerwindow2
./bootstrap
./configure
make
sudo make install
sudo ldconfig
cd ..

cd fedit2
./bootstrap
./configure
make
sudo make install
sudo ldconfig
cd ..

cd Namira-LogAnalyzer
sudo python3 ./setup.py install
cd ..

