#!/bin/bash
sudo apt update
sudo apt upgrade
sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake build-essential libboost-all-dev autoconf automake libtool doxygen graphviz g++ autotools-dev libicu-dev libbz2-dev flex bison libfontconfig1-dev libaudio-dev libxt-dev libglib2.0-dev libxi-dev libxrender-dev python3 python3-pip python3-setuptools python3-numpy python3-matplotlib python-dev-is-python3 


mkdir SS2D

cd SS2D

git clone https://github.com/rcsoccersim/rcssserver
git clone https://github.com/helios-base/soccerwindow2
git clone https://github.com/helios-base/librcsc

cd librcsc
chmod 777 *
./bootstrap
./configure
make -j12
sudo make install
sudo ldconfig
cd ..

cd rcssserver
chmod 777 *
./bootstrap
./configure
make -j12
sudo make install
sudo ldconfig
cd ..

cd soccerwindow2
chmod 777 *
./bootstrap
./configure
make
sudo make install
sudo ldconfig
cd ..
